name: deploy-grinder-main

on:
  push:
    branches:
      - release-main

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        env:
          TARGET_DIR: /home/${{ secrets.SSH_USERNAME }}
          VENV_BIN: venv/bin
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          connect_timeout: 10s
          first_ssh: |-
            mkdir -p logs
            test -d venv || python3.11 -m venv venv

          scp: |-
            './epsilion_wars_mmorpg_automation/*' => $TARGET_DIR/epsilion_wars_mmorpg_automation/
            ./poetry.lock => $TARGET_DIR
            ./pyproject.toml => $TARGET_DIR
            ./README.md => $TARGET_DIR

          last_ssh: |-
            $VENV_BIN/pip install --no-cache-dir poetry pip setuptools --upgrade
            $VENV_BIN/poetry config virtualenvs.create false --local
            $VENV_BIN/poetry install --only main
            $VENV_BIN/pip cache purge

            echo 'telegram_api_id=${{ secrets.TELEGRAM_API_ID }}' > .env
            echo 'telegram_api_hash=${{ secrets.TELEGRAM_API_HASH }}' >> .env
            echo 'anti_captcha_com_apikey=${{ secrets.ANTI_CAPTCHA_APIKEY }}' >> .env
            echo 'minimum_hp_level_for_grinding=95' >> .env
            echo 'stop_if_equip_broken=false' >> .env
            echo 'notifications_enabled=false' >> .env
            echo 'select_random_combo=false' >> .env
            echo 'message_log_limit=400' >> .env

            supervisorctl restart epsa:*
